symptoms = [
    {title: 'Головная боль', description: 'Описание 11111'},
    {title: 'Тошнота', description: 'Описание 22222'},
    {title: 'Учащенное сердцебиение', description: 'Описание 33333'},
    {title: 'Отдышка', description: 'Описание 44444'},
    {title: 'Выделения из носа', description: 'Описание 555555'},
    {title: 'Сухость во рту', description: Faker::WorldOfWarcraft.quote },
    {title: 'Горечь во рту', description: Faker::Matz.quote},
    {title: 'Сыпь', description: ''},
    {title: 'Потемнение в глазах', description: Faker::WorldOfWarcraft.quote },
    {title: 'Апатия', description: ''},
    {title: 'Боль внизу живота', description: Faker::Matz.quote},
    {title: 'Носовое кровотечение', description: ''},
    {title: 'Неприятный запах изо рта', description: Faker::WorldOfWarcraft.quote },
    {title: 'Чихание', description: ''},
    {title: 'Увеличение грудных желез', description: Faker::Matz.quote},
    {title: 'Потеря голоса', description: ''},
    {title: 'Слюна с кровью', description: Faker::WorldOfWarcraft.quote },
    {title: 'Отеки ступней', description: ''},
    {title: 'Зудящая сыпь', description: Faker::WorldOfWarcraft.quote },
    {title: 'Тяжесть в груди', description: ''},
    {title: 'Анальный зуд', description: ''},
    {title: 'Атрофия кожи', description: ''},
    {title: 'Беспокойство', description: Faker::WorldOfWarcraft.quote},
    {title: 'Амнезия', description: ''},
    {title: 'Боль в груди', description: ''},
    {title: 'Боль в области половых органов', description: ''},
    {title: 'Волдыри', description: ''},
    {title: 'Вздутие живота', description: ''},
    {title: 'Воспаленные гланды', description: ''},
    {title: 'Выраженная мышечная слабость', description: Faker::WorldOfWarcraft.quote },
    {title: 'Выпадение волос', description: ''},
    {title: 'Высыпания в виде пузырьков', description: ''},
    {title: 'Газы', description: ''},
    {title: 'Галлюцинации', description: Faker::WorldOfWarcraft.quote },
    {title: 'Головокружение', description: ''},
    {title: 'Депрессия', description: ''},
    {title: 'Диарея', description: ''},
    {title: 'Жажда', description: Faker::WorldOfWarcraft.quote },
    {title: 'Жар', description: ''},
    {title: 'Запор', description: ''},
    {title: 'Изжога', description: ''},
    {title: 'Икота', description: ''},
    {title: 'Изменение цвета ногтей', description: ''},
    {title: 'Кашель', description: ''},
    {title: 'Кашель с кровью', description: ''},
    {title: 'Насморк', description: ''},
    {title: 'Одышка', description: ''},
    {title: 'Ожирение', description: ''},
    {title: 'Охриплость голоса', description: Faker::WorldOfWarcraft.quote },
    {title: 'Рвота', description: ''},
]

symptoms.each do |params|
  Symptom.create!(params)
end
