doctors = [
    {name: 'Натаван', surname: 'Альтшулер', patronymic: 'Ивановна',
     phone: '21111111111', email: 'doctor.1.@doctor.com',
     clinics: [Clinic.first, Clinic.find(5)],
     specializations: [Specialization.find_by_code('therap')],
     grades: [Grade.find(1)]},
    {name: 'София', surname: 'Бугайченко', patronymic: 'Сергеевна',
     phone: '21111111112', email: 'doctor.2.@doctor.com',
     clinics: [Clinic.find(1), Clinic.last],
     specializations: [Specialization.find_by_code('pediatr')],
     grades: [Grade.find(2)]},
    {name: 'Олег', surname: 'Макаров', patronymic: 'Викторович',
     phone: '21111111113', email: 'doctor.3.@doctor.com',
     clinics: [Clinic.find(2)],
     specializations: [Specialization.find_by_code('surg'), Specialization.find_by_code('neuropatholog')],
     grades: [Grade.find(5)]},
    {name: 'Перване', surname: 'Алексерова', patronymic: 'Игоревна',
     phone: '21111111114', email: 'doctor.4.@doctor.com',
     clinics: [Clinic.find(3)],
     specializations: [Specialization.find_by_code('podiatr'), Specialization.find_by_code('orthoped')],
     grades: [Grade.find(4)]},
    {name: 'Whalter', surname: 'White', patronymic: 'Testovich',
     phone: '21111111115', email: 'doctor.5.@doctor.com',
     clinics: [Clinic.find(4), Clinic.find(2), Clinic.find(3)],
     specializations: [Specialization.find_by_code('therap'), Specialization.find_by_code('pediatr')],
     grades: [Grade.find(3), Grade.find(6)]},
    {name: Faker::StarTrek.character, surname: Faker::LordOfTheRings.character, patronymic: Faker::ElderScrolls.race,
     phone: '21111111116', email: 'doctor.6.@doctor.com',
     clinics: [Clinic.find(4), Clinic.find(2), Clinic.find(3)],
     specializations: [Specialization.find_by_code('cardio'), Specialization.find_by_code('surg')],
     grades: [Grade.find(2), Grade.find(6)]},
    {name: Faker::StarTrek.character, surname: Faker::LordOfTheRings.character, patronymic: Faker::ElderScrolls.race,
     phone: '21111111117', email: 'doctor.7.@doctor.com',
     clinics: [Clinic.find(1), Clinic.find(2)],
     specializations: [Specialization.find_by_code('surg')],
     grades: [Grade.find(2)]},
    {name: Faker::StarTrek.character, surname: Faker::LordOfTheRings.character, patronymic: Faker::ElderScrolls.race,
     phone: '21111111118', email: 'doctor.8.@doctor.com',
     clinics: [Clinic.find(4), Clinic.find(2), Clinic.find(3)],
     specializations: [Specialization.find_by_code('gynecolog')],
     grades: [Grade.find(2), Grade.find(6)]},
    {name: Faker::StarTrek.character, surname: Faker::LordOfTheRings.character, patronymic: Faker::ElderScrolls.race,
     phone: '21111111119', email: 'doctor.9.@doctor.com',
     clinics: [Clinic.find(2)],
     specializations: [Specialization.find_by_code('dent')],
     grades: [Grade.find(5)]},
    {name: Faker::StarTrek.character, surname: Faker::LordOfTheRings.character, patronymic: Faker::ElderScrolls.race,
     phone: '211111111110', email: 'doctor.10.@doctor.com',
     clinics: [Clinic.find(1)],
     specializations: [Specialization.find_by_code('dent')],
     grades: [Grade.find(4)]},
    {name: Faker::StarTrek.character, surname: Faker::LordOfTheRings.character, patronymic: Faker::ElderScrolls.race,
     phone: '211111111111', email: 'doctor.11.@doctor.com',
     clinics: [Clinic.find(3)],
     specializations: [Specialization.find_by_code('gynecolog')],
     grades: [Grade.find(2)]},
    {name: Faker::StarTrek.character, surname: Faker::LordOfTheRings.character, patronymic: Faker::ElderScrolls.race,
     phone: '211111111112', email: 'doctor.12.@doctor.com',
     clinics: [Clinic.find(1)],
     specializations: [Specialization.find_by_code('dent')],
     grades: [Grade.find(3)]},
    {name: Faker::StarTrek.character, surname: Faker::LordOfTheRings.character, patronymic: Faker::ElderScrolls.race,
     phone: '211111111113', email: 'doctor.13.@doctor.com',
     clinics: [Clinic.find(5), Clinic.find(7)],
     specializations: [Specialization.find_by_code('gynecolog')],
     grades: [Grade.find(4)]},
    {name: Faker::StarTrek.character, surname: Faker::LordOfTheRings.character, patronymic: Faker::ElderScrolls.race,
     phone: '211111111114', email: 'doctor.14.@doctor.com',
     clinics: [Clinic.find(4), Clinic.find(2)],
     specializations: [Specialization.find_by_code('dent')],
     grades: [Grade.find(2)]},
    {name: Faker::StarTrek.character, surname: Faker::LordOfTheRings.character, patronymic: Faker::ElderScrolls.race,
     phone: '211111111115', email: 'doctor.15.@doctor.com',
     clinics: [Clinic.find(5), Clinic.find(3)],
     specializations: [Specialization.find_by_code('otolaryngolog')],
     grades: [Grade.find(2)]},
    {name: Faker::StarTrek.character, surname: Faker::LordOfTheRings.character, patronymic: Faker::ElderScrolls.race,
     phone: '211111111116', email: 'doctor.16.@doctor.com',
     clinics: [Clinic.find(7)],
     specializations: [Specialization.find_by_code('allerg')],
     grades: [Grade.find(1)]},
    {name: Faker::StarTrek.character, surname: Faker::LordOfTheRings.character, patronymic: Faker::ElderScrolls.race,
     phone: '211111111117', email: 'doctor.17.@doctor.com',
     clinics: [Clinic.find(6), Clinic.find(7)],
     specializations: [Specialization.find_by_code('pediatr')],
     grades: [Grade.find(3)]},
    {name: Faker::StarTrek.character, surname: Faker::LordOfTheRings.character, patronymic: Faker::ElderScrolls.race,
     phone: '211111111118', email: 'doctor.18.@doctor.com',
     clinics: [Clinic.find(6)],
     specializations: [Specialization.find_by_code('therap')],
     grades: [Grade.find(6)]},
    {name: Faker::StarTrek.character, surname: Faker::LordOfTheRings.character, patronymic: Faker::ElderScrolls.race,
     phone: '211111111119', email: 'doctor.19.@doctor.com',
     clinics: [Clinic.find(4)],
     specializations: [Specialization.find_by_code('cardio')],
     grades: [Grade.find(2)]},
    {name: Faker::StarTrek.character, surname: Faker::LordOfTheRings.character, patronymic: Faker::ElderScrolls.race,
     phone: '211111111120', email: 'doctor.20.@doctor.com',
     clinics: [Clinic.find(2)],
     specializations: [Specialization.find_by_code('therap')],
     grades: [Grade.find(1)]},
    {name: Faker::StarTrek.character, surname: Faker::LordOfTheRings.character, patronymic: Faker::ElderScrolls.race,
     phone: '211111111121', email: 'doctor.21.@doctor.com',
     clinics: [Clinic.find(5)],
     specializations: [Specialization.find_by_code('therap')],
     grades: [Grade.find(1)]},
    {name: Faker::StarTrek.character, surname: Faker::LordOfTheRings.character, patronymic: Faker::ElderScrolls.race,
     phone: '211111111122', email: 'doctor.22.@doctor.com',
     clinics: [Clinic.find(6), Clinic.find(7)],
     specializations: [Specialization.find_by_code('neuropatholog')],
     grades: [Grade.find(3)]},
    {name: Faker::StarTrek.character, surname: Faker::LordOfTheRings.character, patronymic: Faker::ElderScrolls.race,
     phone: '211111111123', email: 'doctor.23.@doctor.com',
     clinics: [Clinic.find(6)],
     specializations: [Specialization.find_by_code('rheumatolog')],
     grades: [Grade.find(6)]},
    {name: Faker::StarTrek.character, surname: Faker::LordOfTheRings.character, patronymic: Faker::ElderScrolls.race,
     phone: '211111111124', email: 'doctor.24.@doctor.com',
     clinics: [Clinic.find(4)],
     specializations: [Specialization.find_by_code('ophthalmolog')],
     grades: [Grade.find(2)]},
    {name: Faker::StarTrek.character, surname: Faker::LordOfTheRings.character, patronymic: Faker::ElderScrolls.race,
     phone: '211111111125', email: 'doctor.25.@doctor.com',
     clinics: [Clinic.find(1)],
     specializations: [Specialization.find_by_code('psycholog')],
     grades: [Grade.find(1)]},
    {name: Faker::StarTrek.character, surname: Faker::LordOfTheRings.character, patronymic: Faker::ElderScrolls.race,
     phone: '211111111126', email: 'doctor.26.@doctor.com',
     clinics: [Clinic.find(7)],
     specializations: [Specialization.find_by_code('therap')],
     grades: [Grade.find(1)]},
    {name: Faker::StarTrek.character, surname: Faker::LordOfTheRings.character, patronymic: Faker::ElderScrolls.race,
     phone: '211111111127', email: 'doctor.27.@doctor.com',
     clinics: [Clinic.find(3), Clinic.find(2)],
     specializations: [Specialization.find_by_code('phlebolog')],
     grades: [Grade.find(3)]},
    {name: Faker::StarTrek.character, surname: Faker::LordOfTheRings.character, patronymic: Faker::ElderScrolls.race,
     phone: '211111111128', email: 'doctor.28.@doctor.com',
     clinics: [Clinic.find(6)],
     specializations: [Specialization.find_by_code('androlog')],
     grades: [Grade.find(6)]},
    {name: Faker::StarTrek.character, surname: Faker::LordOfTheRings.character, patronymic: Faker::ElderScrolls.race,
     phone: '211111111129', email: 'doctor.29.@doctor.com',
     clinics: [Clinic.find(4)],
     specializations: [Specialization.find_by_code('phlebolog')],
     grades: [Grade.find(2)]},
    {name: Faker::StarTrek.character, surname: Faker::LordOfTheRings.character, patronymic: Faker::ElderScrolls.race,
     phone: '211111111130', email: 'doctor.30.@doctor.com',
     clinics: [Clinic.find(1)],
     specializations: [Specialization.find_by_code('androlog')],
     grades: [Grade.find(1)]}
]

doctors.each do |params|
  Doctor.create!(params)
end
